---
title: "Does money buy happiness?"
author: "Leilane Cambara"
date: "2024-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

## Introduction

```{r data, include=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)

happiness <- read_excel("C:/Users/leica/Desktop/happiness.xlsx")
HDI <- read_excel("C:/Users/leica/Desktop/happiness.xlsx", sheet = "HDI")
GDP <- read_excel("C:/Users/leica/Desktop/happiness.xlsx", sheet = "GDP")
regions <- read_excel("C:/Users/leica/Desktop/happiness.xlsx", sheet = "Regions")

df = merge(happiness, HDI, by="Country")
df = merge(df, GDP, by="Country")
df = merge(df, regions, by="Country")

```

## Descriptive statistics

```{r describe, echo=FALSE, include=FALSE}

general_stats = df %>%
  summarise(across(c(Happiness_score,HDI,GDP_per_capita), list(mean = mean, min = min, max = max, sd = sd)))

```

```{r correlations, echo=FALSE, results='asis'}

data_correlations = cor(data.frame(df["Happiness_score"], df["HDI"], df["GDP_per_capita"]))
rownames(data_correlations) = c("Happiness score", "HDI", "GDP per capita")
colnames(data_correlations) = c("Happiness score", "HDI", "GDP per capita")
kable(data_correlations, caption = "correlations")

```


```{r describe_by, echo=FALSE}

df %>%
  group_by(World_Region) %>%
  summarise(across(c(Happiness_score,HDI,GDP_per_capita), list(mean = mean, min = min, max = max, sd = sd)))

```

## The relationship between money (GDP per capita) and happiness

```{r scatterplot, echo=FALSE}

scatterPlot <- ggplot(df, aes(GDP_per_capita, Happiness_score, colour=World_Region)) +
  geom_point() +
  labs(x = "GDP per capita", y = "Happiness Score", colour = "World Region") +
  theme_minimal()
scatterPlot

```

## Fitting a model

```{r model, echo=FALSE}

logModel <- lm(unlist(df["Happiness_score"]) ~ log(unlist(df["GDP_per_capita"])))
summary(logModel)

```

```{r model_graph, echo=FALSE}

predictedHappiness <- c(predict(logModel))
GDP_pc <- unlist(df["GDP_per_capita"])
log.df <- data.frame(GDP_pc, predictedHappiness)

scatterPlot <- ggplot() +
  geom_point(data = df, aes(GDP_per_capita, Happiness_score, colour=World_Region)) +
  geom_line(data = log.df, aes(x = GDP_pc, y = predictedHappiness)) +
  labs(x = "GDP per capita", y = "Happiness Score", colour = "World Region") +
  theme_minimal()
scatterPlot

```

